**Fun with Pandas**<br>
Demonstrating how to use pd.DataFrames with pandas.

In [1]:
import pandas as pd

In [5]:
pep_band_df = pd.read_csv("../data/cumulative/DUMB Pep Band Song Statistics - Cumulative.csv")

In [6]:
pep_band_df

,Date,Opponent,Type,Song,Period,Media,Time,Score (Duke-Opponent),Early? (Y/N)
0,2/7,Notre Dame,MBB,Overpass,Pregame,NaN,NaN,0-0,N
1,NaN,NaN,NaN,About Damn Time,Pregame,NaN,NaN,0-0,N
2,NaN,NaN,NaN,Animal,Pregame,NaN,NaN,0-0,N
3,NaN,NaN,NaN,Vehicle,Pregame,NaN,NaN,0-0,N
4,NaN,NaN,NaN,Potential Breakup Song,Pregame,NaN,NaN,0-0,N
...,...,...,...,...,...,...,...,...,...
320,NaN,NaN,NaN,Devil,2H,<12:00,11:39,38-40,N
321,NaN,NaN,NaN,That's What I Want,2H,<12:00,11:39,38-40,N
322,NaN,NaN,NaN,Everytime,2H,NaN,8:19,40-48,N
323,NaN,NaN,NaN,Sail,2H,<4:00,1:39,54-65,N
324,NaN,NaN,NaN,Blue & White,Postgame,NaN,NaN,64-76,N

In [7]:
pep_band_df.dtypes

Date                     object
Opponent                 object
Type                     object
Song                     object
Period                   object
Media                    object
Time                     object
Score (Duke-Opponent)    object
Early? (Y/N)             object
dtype: object

In [50]:
# Option 1: Set the index to the song name
# pep_band_song_series = pep_band_df.groupby("Song").size()
# song_column_names = ["Count"]

# pep_band_song_df = pd.DataFrame(pep_band_song_series, columns=song_column_names)

# Option 2: Set the index to the group key
pep_band_song_series = pep_band_df.groupby("Song").size().reset_index(name="Count")
pep_band_song_df = pd.DataFrame(pep_band_song_series)

In [51]:
pep_band_song_df.index

RangeIndex(start=0, stop=46, step=1)

In [52]:
pep_band_song_df

                        Song  Count
0            About Damn Time      4
1                     Animal      1
2               Blue & White     35
3           Break Your Heart      2
4                      Can't     33
5                  Chameleon      1
6              Crazy in Love      1
7                   D. Ditty      3
8                    DJamite      3
9            Dance the Night     11
10             Dear Old Duke      9
11                     Devil     24
12                 Disturbia      1
13                 Everytime     13
14                       Fat      2
15               Fight Fight     22
16                      Fire      1
17                 Get It On      1
18              Igor's Theme      1
19             Industry Baby      1
20             Love Runs Out      3
21  Love from the Other Side     10
22              Lucky Strike      7
23                    Mortal      8
24               Ms. Jackson      1
25                  Overpass      8
26    Potential Breakup Song      4
27                   Pumpkin      9
28          Raise Your Glass      4
29              Rock Lobster      1
30              Runaway Baby      9
31                      Sail      8
32                    Scream      5
33          Somebody Told Me      3
34                     Spell      7
35               Stacy's Mom      2
36                    Sucker      3
37                   T. gogo      4
38                 That That      5
39        That's What I Want     12
40  The Star-Spangled Banner      2
41               Uma Thurman      8
42                   Vehicle      3
43                   Wipeout      7
44                  Zing It!     19
45           good 4 business      4

In [55]:
pd.DataFrame({"num": [pep_band_song_df["Count"].max()]})

   num
0   35